//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;


namespace AssemblyCSharp
{
	public class PotentialSolution
	{
			public List<KeyCode> KeyCodes;
		public float Score;

		public void GenerateRandom()
		{
			UnityEngine.Random.seed = DateTime.UtcNow.Millisecond * DateTime.UtcNow.Second;

			KeyCodes = new List<KeyCode> ();

			for (int i=0; i < 700; i++)
			{
				int character = UnityEngine.Random.Range (0, 3);

				switch(character)
				{
				case 0:
					KeyCodes.Add(KeyCode.X);
					break;
				case 1:
					KeyCodes.Add(KeyCode.W);
					break;
				case 2: 
					KeyCodes.Add(KeyCode.E);
					break;
				}
			}
		}
	
	}
}

